type: module
name: Product Scan
description: 'Product scan by Custom Module.'
package: Custom
core: 8.x
core_version_requirement: ^8 || ^9

dependencies:
  - block



#configure: music_world.music_video_configuration